default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: db
  username: postgres
  database: skeleton_development

test:
  <<: *default
  host: db
  username: postgres
  database: skeleton_test
  min_messages: notice

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
